services:
  cardz-backend:
    image: cardz-backend
    ports:
      - "3000:3000"
    networks:
      - cardz-app
  cardz-frontend:
    image: cardz-frontend
    stdin_open: true
    ports:
      - "5173:5173"
    networks:
      - cardz-app
networks:
  cardz-app:
    driver: bridge
